teamWaggle/Waggle-server

spy.log, src/main/java/com/example/waggle/comment/service/ReplyServiceImpl.java
1. 댓글 조회 로직을 `getReplyById` 메서드로 분리
2. 언급 추가 로직을 `addMentionsToReply` 메서드로 분리
=> Refactor: ReplyServiceImpl 리팩토링

README.md, spy.log, src/main/java/com/example/waggle/board/helpU/controller/HelpUApiController.java, src/main/java/com/example/waggle/board/question/controller/QuestionApiController.java, src/main/java/com/example/waggle/board/story/controller/StoryApiController.java, src/main/java/com/example/waggle/comment/controller/CommentApiController.java, src/main/java/com/example/waggle/comment/controller/ReplyApiController.java, src/main/java/com/example/waggle/comment/domain/Reply.java, src/main/java/com/example/waggle/comment/dto/ReplyViewDto.java, src/main/java/com/example/waggle/comment/dto/ReplyWriteDto.java, src/main/java/com/example/waggle/comment/service/ReplyServiceImpl.java, src/main/java/com/example/waggle/member/controller/MemberApiController.java, src/main/java/com/example/waggle/memberMention/controller/memberMentionApiController.java, src/main/java/com/example/waggle/memberMention/repository/MemberMentionRepository.java, src/main/java/com/example/waggle/mention/controller/MentionApiController.java, src/main/java/com/example/waggle/mention/domain/Mention.java, src/main/java/com/example/waggle/mention/repository/MentionRepository.java, src/main/java/com/example/waggle/recommend/controller/RecommendApiController.java, src/test/java/com/example/waggle/comment/repository/CommentRepositoryTest.java, src/test/java/com/example/waggle/reply/service/ReplyServiceTest.java
1. 불필요한 줄바꿈 제거
2. RESTful 규칙에 따라 요청 URL 수정
3. 명확성을 위해 ResponseEntity<> 내부의 타입을 명시
4. 업데이트된 사항을 반영하여 메서드 이름도 수정
=> API Controller RESTful 원칙에 맞게 리팩토링

src/main/java/com/example/waggle/domain/board/answer/service/AnswerCommandService.java, src/main/java/com/example/waggle/domain/board/answer/service/AnswerCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandService.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandService.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandServiceImpl.java, src/main/java/com/example/waggle/domain/comment/entity/Reply.java, src/main/java/com/example/waggle/domain/comment/service/reply/ReplyCommandService.java, src/main/java/com/example/waggle/domain/comment/service/reply/ReplyCommandServiceImpl.java, src/main/java/com/example/waggle/domain/mention/entity/Mention.java, src/main/java/com/example/waggle/web/converter/ReplyConverter.java, src/main/java/com/example/waggle/web/dto/reply/ReplyRequest.java, src/main/java/com/example/waggle/web/dto/reply/ReplyResponse.java
> member mention in reply feat
- [issue/103](https://github.com/teamWaggle/Waggle-server/issues/103)
- [notion/backend/tasktracker/member mention](https://www.notion.so/member-mention-68334eb8e0c540c3a28c20a2e06bfa36?pvs=4)
=> [Feat/#103] member mention feat

build.gradle, src/main/java/com/example/waggle/domain/follow/service/FollowCommandService.java, src/main/java/com/example/waggle/domain/follow/service/FollowCommandServiceImpl.java, src/main/java/com/example/waggle/global/config/SwaggerConfig.java, src/main/java/com/example/waggle/global/payload/code/ErrorStatus.java, src/main/java/com/example/waggle/global/security/TokenServiceImpl.java, src/main/java/com/example/waggle/global/security/annotation/AuthUser.java, src/main/java/com/example/waggle/web/controller/FollowApiController.java, src/test/java/com/example/waggle/follow/service/FollowServiceTest.java, src/test/java/com/example/waggle/member/service/MemberServiceImplTest.java
> 1. not allow following myself
> 2. Parameter(hidden=true) accept in global
> 3. if login failed, use custom exception
- https://github.com/teamWaggle/Waggle-server/issues/109
- [notion/tasktracker/followRefactor](https://www.notion.so/followApiController-ref-9f7ed00b3ee04bfbbff9da3a45d3193e?pvs=4)
=> [Refactor/#109] refactor follow logic and else

src/main/java/com/example/waggle/global/config/SecurityConfig.java
> logout authentication permit
- []()
=> [HotFix] permit /api/tokens logout api

src/main/java/com/example/waggle/domain/member/service/MemberCommandService.java, src/main/java/com/example/waggle/domain/member/service/MemberCommandServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendQueryService.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendQueryServiceImpl.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleCommandServiceImpl.java, src/main/java/com/example/waggle/global/payload/code/ErrorStatus.java, src/main/java/com/example/waggle/web/controller/AnswerApiController.java, src/main/java/com/example/waggle/web/controller/MemberApiController.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/controller/StoryApiController.java, src/main/java/com/example/waggle/web/converter/AnswerConverter.java, src/main/java/com/example/waggle/web/converter/CommentConverter.java, src/main/java/com/example/waggle/web/converter/QuestionConverter.java, src/main/java/com/example/waggle/web/converter/ReplyConverter.java, src/main/java/com/example/waggle/web/converter/ScheduleConverter.java, src/main/java/com/example/waggle/web/converter/SirenConverter.java, src/main/java/com/example/waggle/web/converter/StoryConverter.java, src/main/java/com/example/waggle/web/dto/answer/AnswerResponse.java, src/main/java/com/example/waggle/web/dto/comment/CommentResponse.java, src/main/java/com/example/waggle/web/dto/member/VerifyMailRequest.java, src/main/java/com/example/waggle/web/dto/question/QuestionResponse.java, src/main/java/com/example/waggle/web/dto/reply/ReplyResponse.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleResponse.java, src/main/java/com/example/waggle/web/dto/schedule/TeamResponse.java, src/main/java/com/example/waggle/web/dto/siren/SirenResponse.java, src/main/java/com/example/waggle/web/dto/story/StoryResponse.java
> 1. add email field in send email api
> 2. enable writer remove member_schedule
> 3. add field checking mine
> 4. convert boolean type from primitive to reference(result : mine -> isMine, recommend -> isRecommend)
- https://github.com/teamWaggle/Waggle-server/issues/118
=> [Refactor/#118]refactor based on front-end request

src/main/java/com/example/waggle/domain/member/entity/Member.java, src/main/java/com/example/waggle/domain/member/repository/MemberRepository.java, src/main/java/com/example/waggle/domain/member/service/MemberCommandService.java, src/main/java/com/example/waggle/domain/member/service/MemberCommandServiceImpl.java, src/main/java/com/example/waggle/domain/member/service/MemberQueryService.java, src/main/java/com/example/waggle/domain/member/service/MemberQueryServiceImpl.java, src/main/java/com/example/waggle/global/util/EmailUtil.java, src/main/java/com/example/waggle/web/controller/MemberApiController.java, src/main/java/com/example/waggle/web/converter/MemberConverter.java, src/main/java/com/example/waggle/web/dto/member/MemberRequest.java, src/main/java/com/example/waggle/web/dto/member/MemberResponse.java, src/test/java/com/example/waggle/member/service/MemberServiceImplTest.java
> find member info (email & password)
- https://github.com/teamWaggle/Waggle-server/issues/132
=> [Feat/#132] find Email & change Password

src/main/java/com/example/waggle/domain/board/question/entity/Question.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/siren/entity/Siren.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandServiceImpl.java
=> [Hotfix] Resolve Conflicts

src/main/java/com/example/waggle/web/controller/MemberApiController.java
> convert pathvariable username->memberId when member read
- []()
=> [HotFix] convert pathvariable username->memberId when member read

src/main/java/com/example/waggle/domain/media/service/MediaCommandServiceImpl.java, src/main/java/com/example/waggle/domain/member/entity/Member.java, src/main/java/com/example/waggle/domain/member/service/MemberCommandService.java, src/main/java/com/example/waggle/domain/member/service/MemberCommandServiceImpl.java, src/main/java/com/example/waggle/domain/pet/entity/Pet.java, src/main/java/com/example/waggle/domain/pet/service/PetCommandService.java, src/main/java/com/example/waggle/domain/pet/service/PetCommandServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/repository/RecommendRepository.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendCommandServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendQueryService.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendQueryServiceImpl.java, src/main/java/com/example/waggle/global/payload/code/ErrorStatus.java, src/main/java/com/example/waggle/global/security/oauth2/CustomOAuth2UserService.java, src/main/java/com/example/waggle/global/security/service/TokenServiceImpl.java, src/main/java/com/example/waggle/global/util/MediaUtil.java, src/main/java/com/example/waggle/global/util/ObjectUtil.java, src/main/java/com/example/waggle/web/controller/AnswerApiController.java, src/main/java/com/example/waggle/web/controller/MemberApiController.java, src/main/java/com/example/waggle/web/controller/PetApiController.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/controller/StoryApiController.java, src/main/java/com/example/waggle/web/dto/answer/AnswerResponse.java, src/main/java/com/example/waggle/web/dto/member/MemberRequest.java, src/main/java/com/example/waggle/web/dto/pet/PetRequest.java, src/main/java/com/example/waggle/web/dto/question/QuestionResponse.java, src/main/java/com/example/waggle/web/dto/recommend/RecommendResponse.java, src/main/java/com/example/waggle/web/dto/siren/SirenResponse.java, src/main/java/com/example/waggle/web/dto/story/StoryResponse.java
> refactor by request
> 1. remove profileImg in storyDetailDto
> 2. convert null checking -> objectUtil
> 3. convert findByEmail query in OAUTH2
> 4. add argument profileImgUrl in service (member, pet)
> 5. add recommendation Info & refactor recommendQueryServide
- https://github.com/teamWaggle/Waggle-server/issues/142
=> [Refactor/#142]refactor by request

src/main/java/com/example/waggle/domain/schedule/repository/ParticipationRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleCommandServiceImpl.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamCommandServiceImpl.java, src/main/java/com/example/waggle/global/payload/code/ErrorStatus.java
> team&schedule logic
- https://github.com/teamWaggle/Waggle-server/issues/144
=> [Refactor/#144] team&schedule logic

src/main/java/com/example/waggle/domain/board/question/entity/Question.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandService.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionQueryServiceImpl.java, src/main/java/com/example/waggle/domain/board/siren/entity/Siren.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandService.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenQueryServiceImpl.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/converter/QuestionConverter.java, src/main/java/com/example/waggle/web/converter/SirenConverter.java, src/main/java/com/example/waggle/web/dto/question/QuestionResponse.java, src/main/java/com/example/waggle/web/dto/siren/SirenResponse.java
> Implement View Count Tracking for Siren, Question
- [https://github.com/teamWaggle/Waggle-server/issues/159](https://github.com/teamWaggle/Waggle-server/issues/159)
=> [Feat/#159] Implement View Count Tracking for Siren, Question

src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandService.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandService.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenCommandServiceImpl.java, src/main/java/com/example/waggle/domain/board/story/service/StoryCommandService.java, src/main/java/com/example/waggle/domain/board/story/service/StoryCommandServiceImpl.java, src/main/java/com/example/waggle/domain/media/service/MediaCommandService.java, src/main/java/com/example/waggle/domain/media/service/MediaCommandServiceImpl.java, src/main/java/com/example/waggle/global/config/SecurityConfig.java, src/main/java/com/example/waggle/web/controller/MediaApiController.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/controller/StoryApiController.java, src/main/java/com/example/waggle/web/converter/MediaConverter.java, src/main/java/com/example/waggle/web/dto/answer/AnswerRequest.java, src/main/java/com/example/waggle/web/dto/media/MediaRequest.java, src/main/java/com/example/waggle/web/dto/media/MediaResponse.java, src/main/java/com/example/waggle/web/dto/question/QuestionRequest.java, src/main/java/com/example/waggle/web/dto/siren/SirenRequest.java, src/main/java/com/example/waggle/web/dto/story/StoryRequest.java
> when update board, media have many problem because order and object type is different. 
> so logic is very complicated.
> this time, divide upload file & save imgUrl in database 
- https://github.com/teamWaggle/Waggle-server/issues/154
=> [Refactor/#154] refactor update board api for media

src/main/java/com/example/waggle/domain/media/service/MediaCommandService.java, src/main/java/com/example/waggle/domain/media/service/MediaCommandServiceImpl.java, src/main/java/com/example/waggle/web/controller/MediaApiController.java
> refactor removing medai by scheduled because of wrong type
- [x] 🚑 Hot Fix
=> [HotFix] refactor removing medai by scheduled because of wrong type

src/main/java/com/example/waggle/domain/board/siren/repository/SirenRepository.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenQueryService.java, src/main/java/com/example/waggle/domain/board/siren/service/SirenQueryServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/repository/RecommendRepository.java, src/main/java/com/example/waggle/web/controller/RecommendApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/converter/SirenConverter.java, src/main/java/com/example/waggle/web/dto/siren/SirenResponse.java
> 대표 사이렌 3개를 조회하는 API를 구현했습니다.
1. ResolutionStatus가 UNRESOLVED인 사이렌 게시물을 우선 정렬
2. ResolutionStatus가 동일한 경우, 각 사이렌에 대한 추천 수가 많은 순으로 정렬
3. 상위 3개의 사이렌 반환
API 호출 시 정상적으로 정렬된 데이터를 확인할 수 있었습니다.
```json
{
"isSuccess": true,
"code": 2000,
"message": "성공",
"result": {
"sirenList": [
{
"boardId": 104,
"title": "string",
"thumbnail": null,
"createdDate": "2024-03-16T15:49:19.21977",
"lostLocate": "string",
"category": "FIND_PET",
"status": "UNRESOLVED",
"recommendationInfo": {
"isRecommend": true,
"recommendCount": 1
}
},
{
"boardId": 1,
"title": "string",
"thumbnail": null,
"createdDate": "2024-03-12T13:43:19.842015",
"lostLocate": "string",
"category": "FIND_PET",
"status": "UNRESOLVED",
"recommendationInfo": {
"isRecommend": false,
"recommendCount": 0
}
},
{
"boardId": 102,
"title": "string", …
```
=> [Feat/#145]  Implement API for Representative Siren List

src/main/java/com/example/waggle/domain/media/service/MediaCommandServiceImpl.java
=> [HotFix] change removing file period

src/main/java/com/example/waggle/domain/board/question/service/QuestionQueryService.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionQueryServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/repository/RecommendRepository.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/converter/QuestionConverter.java, src/main/java/com/example/waggle/web/dto/question/QuestionResponse.java
> 대표 질문 3개를 조회하는 API를 구현했습니다.
1. 각 질문에 대한 추천 수가 많은 순으로 정렬
3. 상위 3개의 질문 반환
API 호출 시 정상적으로 정렬된 데이터를 확인할 수 있었습니다.
```json
{
"isSuccess": true,
"code": 2000,
"message": "성공",
"result": {
"questionList": [
{
"boardId": 153,
"title": "string",
"status": "UNRESOLVED",
"createdDate": "2024-03-20T02:06:37.723597",
"hashtagList": [
"string"
],
"member": {
"memberId": 1952,
"userUrl": "wagglec181c",
"nickname": "nickname9441d",
"profileImgUrl": null
},
"recommendationInfo": {
"isRecommend": true,
"recommendCount": 2
}
},
{
"boardId": 152,
"title": "string",
"status": "UNRESOLVED",
"createdDate": "2024-03-20T02:06:34.883839",
"hashtagList": [
"string"
],
"member": {
"memberId": 1952,
"userUrl": "wagglec181c",
"nickname": "nickname9441d",
"profileImgUrl": null
},
"recommendationInfo": {
"isRecommend": …
```
=> [Feat/#166] Implement API for Representative Question List

src/main/java/com/example/waggle/domain/board/question/service/QuestionQueryService.java, src/main/java/com/example/waggle/domain/board/question/service/QuestionQueryServiceImpl.java, src/main/java/com/example/waggle/domain/media/service/MediaCommandServiceImpl.java, src/main/java/com/example/waggle/domain/recommend/repository/RecommendRepository.java, src/main/java/com/example/waggle/global/util/PageUtil.java, src/main/java/com/example/waggle/web/controller/MemberApiController.java, src/main/java/com/example/waggle/web/controller/PetApiController.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/controller/SirenApiController.java, src/main/java/com/example/waggle/web/controller/StoryApiController.java, src/main/java/com/example/waggle/web/controller/TeamApiController.java, src/main/java/com/example/waggle/web/converter/QuestionConverter.java, src/main/java/com/example/waggle/web/converter/StoryConverter.java, src/main/java/com/example/waggle/web/dto/question/QuestionResponse.java, src/main/java/com/example/waggle/web/dto/story/StoryResponse.java
> 1. convert transfer type from application/json to multipart/form-data when related to media
> 2. add Question api of reading top 3
> 3. set pagination of story
- https://github.com/teamWaggle/Waggle-server/issues/173
- https://github.com/teamWaggle/Waggle-server/issues/166
- https://github.com/teamWaggle/Waggle-server/issues/175
=> Merge develop to main

src/main/java/com/example/waggle/domain/schedule/entity/Schedule.java, src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/repository/ScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleCommandServiceImpl.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryServiceImpl.java, src/main/java/com/example/waggle/global/annotation/valid/enums/EnumValidator.java, src/main/java/com/example/waggle/global/annotation/valid/enums/ValidEnum.java, src/main/java/com/example/waggle/global/annotation/valid/localTime/LocalTimeValidator.java, src/main/java/com/example/waggle/global/annotation/valid/localTime/ValidTimeForm.java, src/main/java/com/example/waggle/global/util/ScheduleUtil.java, src/main/java/com/example/waggle/web/controller/ScheduleApiController.java, src/main/java/com/example/waggle/web/converter/ScheduleConverter.java, src/main/java/com/example/waggle/web/converter/TeamConverter.java, src/main/java/com/example/waggle/web/dto/pet/PetRequest.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleRequest.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleResponse.java, src/main/java/com/example/waggle/web/dto/schedule/TeamRequest.java, src/main/java/com/example/waggle/web/dto/schedule/TeamResponse.java, src/main/java/com/example/waggle/web/dto/siren/SirenRequest.java
> 1. swagger summary description 
> 2. divide date & time when write & read schedule
> 3. add teamId in Response
> 4. add custom annotation of valid time parse
- https://github.com/teamWaggle/Waggle-server/issues/180
=> [Refactor/#180] Refactor schedule & team api following request from front

src/main/java/com/example/waggle/domain/recommend/service/RecommendCommandServiceImplV2.java, src/main/java/com/example/waggle/domain/recommend/service/RecommendQueryServiceImplV2.java, src/main/java/com/example/waggle/global/config/SecurityConfig.java, src/main/java/com/example/waggle/web/controller/RecommendApiController.java
> 1. add init logic when validateInitRecommend not throw exception
> 2. refactor read member who recommend board
- https://github.com/teamWaggle/Waggle-server/issues/183
=> [Refactor/#183] add init logic when validateInitRecommend not throw exception

src/main/java/com/example/waggle/domain/schedule/entity/Team.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamCommandService.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamCommandServiceImpl.java, src/main/java/com/example/waggle/web/controller/TeamApiController.java, src/main/java/com/example/waggle/web/converter/ScheduleConverter.java, src/main/java/com/example/waggle/web/converter/TeamConverter.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleResponse.java, src/main/java/com/example/waggle/web/dto/schedule/TeamRequest.java
> schedule & team api request from front-end
- https://github.com/teamWaggle/Waggle-server/issues/185
=> [Refactor/#185] schedule & team api request from front-end

src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/repository/ParticipationRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryServiceImpl.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryServiceImpl.java, src/main/java/com/example/waggle/web/controller/ScheduleApiController.java, src/main/java/com/example/waggle/web/controller/TeamApiController.java, src/main/java/com/example/waggle/web/converter/ScheduleConverter.java, src/main/java/com/example/waggle/web/converter/TeamConverter.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleResponse.java, src/main/java/com/example/waggle/web/dto/schedule/TeamResponse.java
> Enhancements to Team and Schedule API
- [https://github.com/teamWaggle/Waggle-server/issues/193](https://github.com/teamWaggle/Waggle-server/issues/193)
=> [Feat/#193] Enhancements to Team and Schedule API

src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryServiceImpl.java, src/main/java/com/example/waggle/web/controller/TeamApiController.java
> Update participation status check to return ACCEPT for team members
=> [HotFix] Update participation status check to return ACCEPT for team members

src/main/java/com/example/waggle/domain/member/service/MemberQueryServiceImpl.java, src/main/java/com/example/waggle/global/config/SecurityConfig.java, src/main/java/com/example/waggle/global/security/exception/JwtAuthenticationEntryPoint.java, src/main/java/com/example/waggle/global/security/oauth2/handler/OAuth2AuthenticationFailureHandler.java, src/main/java/com/example/waggle/global/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java, src/main/java/com/example/waggle/web/controller/MemberApiController.java, src/main/java/com/example/waggle/web/controller/TokenApiController.java, src/main/java/com/example/waggle/web/converter/MemberConverter.java, src/main/java/com/example/waggle/web/dto/member/MemberResponse.java
> hotfix error of update content
- https://github.com/teamWaggle/Waggle-server/issues/206
=> [Hotfix/#206] hotfix error of update content

src/main/java/com/example/waggle/domain/board/siren/service/SirenQueryServiceImpl.java, src/main/java/com/example/waggle/domain/board/story/service/StoryQueryServiceImpl.java
=> [HotFix] change username to userurl

src/main/java/com/example/waggle/global/security/oauth2/handler/OAuth2AuthenticationSuccessHandler.java
> add isGuest param when social login
- https://github.com/teamWaggle/Waggle-server/issues/209
=> [Refactor/#209] add isGuest param when social login

src/main/java/com/example/waggle/domain/schedule/repository/TeamMemberRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryServiceImpl.java, src/main/java/com/example/waggle/web/controller/ScheduleApiController.java
> Add Overlapped Schedule Logic to Paged API
=> [HotFix] Add Overlapped Schedule Logic to Paged API

src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryServiceImpl.java
> Fix Overlapped Schedule Logic
=> [HotFix] Fix Overlapped Schedule Logic

src/main/java/com/example/waggle/domain/conversation/repository/CommentRepository.java, src/main/java/com/example/waggle/domain/conversation/service/comment/CommentQueryService.java, src/main/java/com/example/waggle/domain/conversation/service/comment/CommentQueryServiceImpl.java, src/main/java/com/example/waggle/global/util/MediaUtil.java, src/main/java/com/example/waggle/web/controller/CommentApiController.java, src/main/java/com/example/waggle/web/controller/PetApiController.java, src/main/java/com/example/waggle/web/controller/QuestionApiController.java, src/main/java/com/example/waggle/web/converter/PetConverter.java, src/main/resources/application.yml
> 1. set default Img (member Profile, pet Profile)
> 2. convert response data of pet
> 3. add read comment of auth user
> 4. convert Pagination option when read Question List
- https://github.com/teamWaggle/Waggle-server/issues/215
=> [Refactor/#215] request from front-end

.gitignore, build.gradle, src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleQueryRepository.java, src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleQueryRepositoryImpl.java, src/main/java/com/example/waggle/domain/schedule/repository/MemberScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/repository/ScheduleRepository.java, src/main/java/com/example/waggle/domain/schedule/repository/TeamRepository.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/schedule/ScheduleQueryServiceImpl.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryService.java, src/main/java/com/example/waggle/domain/schedule/service/team/TeamQueryServiceImpl.java, src/main/java/com/example/waggle/global/config/QueryDslConfig.java, src/main/java/com/example/waggle/global/config/SecurityConfig.java, src/main/java/com/example/waggle/web/controller/ScheduleApiController.java, src/main/java/com/example/waggle/web/controller/TeamApiController.java, src/main/java/com/example/waggle/web/converter/ScheduleConverter.java, src/main/java/com/example/waggle/web/converter/TeamConverter.java, src/main/java/com/example/waggle/web/dto/schedule/ScheduleResponse.java, src/main/java/com/example/waggle/web/dto/schedule/TeamResponse.java, src/test/java/com/example/waggle/domain/recommend/service/RecommendCommandServiceImplV2Test.java
> 1.  add search team api
> 2. add recommend team api
> 3. edit overlapped schedule api
> 4. convert schedule member -> schedule Owner
> 5. convert team leader -> team teamLeader
- https://github.com/teamWaggle/Waggle-server/issues/220
=> [Refactor/#220] refactor team&schedule api
